// KamKhoj Play — bundled content: word lists, quiz packs, Nepal questions,
// typing corpus. No network. Kept in one maintainable module.
//
// Dataset sizes (kept above 100 items per game pool so repeats are rare):
//   SCRAMBLE_WORDS  112 | HANGMAN_WORDS 104 | QUIZ_QUESTIONS 104
//   NEPAL_QUESTIONS 108 | TYPING_WORDS  300+

export interface ScrambleWord {
  word: string;
  hint: string;
  category: string;
}

export const SCRAMBLE_WORDS: ScrambleWord[] = [
  { word: "EVEREST", hint: "World's tallest peak, in Nepal", category: "Nepal" },
  { word: "POKHARA", hint: "Lakeside city beneath the Annapurnas", category: "Nepal" },
  { word: "MOMO", hint: "Beloved Nepali dumpling", category: "Nepal" },
  { word: "KATHMANDU", hint: "Capital city of Nepal", category: "Nepal" },
  { word: "LUMBINI", hint: "Birthplace of the Buddha", category: "Nepal" },
  { word: "RHODODENDRON", hint: "Nepal's national flower (lali gurans)", category: "Nepal" },
  { word: "DHAKA", hint: "Traditional Nepali woven fabric", category: "Nepal" },
  { word: "YAK", hint: "High-altitude Himalayan animal", category: "Nepal" },
  { word: "CHITWAN", hint: "National park famous for rhinos", category: "Nepal" },
  { word: "GORKHA", hint: "Historic hill kingdom of Nepal", category: "Nepal" },
  { word: "MUSTANG", hint: "Trans-Himalayan district of Nepal", category: "Nepal" },
  { word: "BHAKTAPUR", hint: "Ancient Newar city of devotees", category: "Nepal" },
  { word: "PATAN", hint: "City of fine arts, Lalitpur", category: "Nepal" },
  { word: "JANAKPUR", hint: "City of the Janaki temple", category: "Nepal" },
  { word: "DANPHE", hint: "Nepal's national bird", category: "Nepal" },
  { word: "SHERPA", hint: "Himalayan mountaineering community", category: "Nepal" },
  { word: "COMPUTER", hint: "It runs your code", category: "Technology" },
  { word: "KEYBOARD", hint: "You type on it", category: "Technology" },
  { word: "INTERNET", hint: "Global network", category: "Technology" },
  { word: "SOFTWARE", hint: "Programs, collectively", category: "Technology" },
  { word: "DATABASE", hint: "Where structured data lives", category: "Technology" },
  { word: "PYTHON", hint: "A popular programming language", category: "Technology" },
  { word: "BROWSER", hint: "Chrome, Firefox, Safari…", category: "Technology" },
  { word: "LAPTOP", hint: "Portable computer", category: "Technology" },
  { word: "SERVER", hint: "Serves data over a network", category: "Technology" },
  { word: "ROUTER", hint: "Directs network traffic", category: "Technology" },
  { word: "PIXEL", hint: "Smallest dot on a screen", category: "Technology" },
  { word: "ALGORITHM", hint: "Step-by-step procedure", category: "Technology" },
  { word: "SMARTPHONE", hint: "A computer that fits in your pocket", category: "Technology" },
  { word: "ROBOT", hint: "Programmable machine that moves", category: "Technology" },
  { word: "TABLET", hint: "Touchscreen slab computer", category: "Technology" },
  { word: "PRINTER", hint: "It puts digital pages on paper", category: "Technology" },
  { word: "ELEPHANT", hint: "Largest land animal", category: "Animals" },
  { word: "RHINOCEROS", hint: "One-horned animal of Chitwan", category: "Animals" },
  { word: "LEOPARD", hint: "Spotted big cat", category: "Animals" },
  { word: "DOLPHIN", hint: "Intelligent marine mammal", category: "Animals" },
  { word: "PENGUIN", hint: "Flightless Antarctic bird", category: "Animals" },
  { word: "CROCODILE", hint: "Armoured river reptile", category: "Animals" },
  { word: "TIGER", hint: "Striped big cat of the Terai", category: "Animals" },
  { word: "PANDA", hint: "Bamboo-eating bear", category: "Animals" },
  { word: "GIRAFFE", hint: "Longest-necked animal", category: "Animals" },
  { word: "ZEBRA", hint: "Striped horse-like animal", category: "Animals" },
  { word: "KANGAROO", hint: "Hopping Australian marsupial", category: "Animals" },
  { word: "MONKEY", hint: "Tree-swinging primate", category: "Animals" },
  { word: "COBRA", hint: "Hooded venomous snake", category: "Animals" },
  { word: "EAGLE", hint: "Sharp-eyed bird of prey", category: "Animals" },
  { word: "WHALE", hint: "Largest animal on Earth", category: "Animals" },
  { word: "CAMEL", hint: "Desert ship with humps", category: "Animals" },
  { word: "FRANCE", hint: "Eiffel Tower country", category: "Countries" },
  { word: "JAPAN", hint: "Land of the rising sun", category: "Countries" },
  { word: "BRAZIL", hint: "Largest South American country", category: "Countries" },
  { word: "EGYPT", hint: "Home of the pyramids", category: "Countries" },
  { word: "CANADA", hint: "Maple leaf country", category: "Countries" },
  { word: "NEPAL", hint: "Himalayan nation, home of Everest", category: "Countries" },
  { word: "INDIA", hint: "Nepal's southern neighbour", category: "Countries" },
  { word: "CHINA", hint: "Nepal's northern neighbour", category: "Countries" },
  { word: "BHUTAN", hint: "Himalayan kingdom east of Nepal", category: "Countries" },
  { word: "ITALY", hint: "Boot-shaped European country", category: "Countries" },
  { word: "SPAIN", hint: "Famous for flamenco and paella", category: "Countries" },
  { word: "MEXICO", hint: "Country famous for tacos", category: "Countries" },
  { word: "THAILAND", hint: "Land of smiles", category: "Countries" },
  { word: "GREECE", hint: "Birthplace of the Olympics", category: "Countries" },
  { word: "PERU", hint: "Home of Machu Picchu", category: "Countries" },
  { word: "KENYA", hint: "Famous for safaris", category: "Countries" },
  { word: "PIZZA", hint: "Cheesy Italian dish", category: "Food" },
  { word: "CHOCOLATE", hint: "Sweet cocoa treat", category: "Food" },
  { word: "SANDWICH", hint: "Food between bread slices", category: "Food" },
  { word: "NOODLES", hint: "Long thin pasta-like food", category: "Food" },
  { word: "BURGER", hint: "Patty served in a bun", category: "Food" },
  { word: "PANCAKE", hint: "Flat cake from a griddle", category: "Food" },
  { word: "CHEESE", hint: "Made from milk, aged for flavour", category: "Food" },
  { word: "BREAD", hint: "Baked staple loaf", category: "Food" },
  { word: "BANANA", hint: "Curved yellow fruit", category: "Food" },
  { word: "ORANGE", hint: "Citrus fruit and colour", category: "Food" },
  { word: "POTATO", hint: "Underground vegetable, fry favourite", category: "Food" },
  { word: "HONEY", hint: "Sweet syrup made by bees", category: "Food" },
  { word: "BUTTER", hint: "Creamy spread for bread", category: "Food" },
  { word: "PASTA", hint: "Italian noodles", category: "Food" },
  { word: "MANGO", hint: "Sweet tropical stone fruit", category: "Food" },
  { word: "COCONUT", hint: "Hard-shelled tropical fruit", category: "Food" },
  { word: "FOOTBALL", hint: "The world's most played sport", category: "Sports" },
  { word: "CRICKET", hint: "Bat-and-ball summer sport", category: "Sports" },
  { word: "TENNIS", hint: "Racket sport with a net", category: "Sports" },
  { word: "MARATHON", hint: "Very long running race", category: "Sports" },
  { word: "CHESS", hint: "Board game of kings", category: "Sports" },
  { word: "BOXING", hint: "Fighting sport with gloves", category: "Sports" },
  { word: "RUGBY", hint: "Oval-ball contact sport", category: "Sports" },
  { word: "GOLF", hint: "Club-and-ball course sport", category: "Sports" },
  { word: "KARATE", hint: "Japanese empty-hand martial art", category: "Sports" },
  { word: "JUDO", hint: "Gentle-way grappling art", category: "Sports" },
  { word: "SWIMMING", hint: "Racing through water", category: "Sports" },
  { word: "CYCLING", hint: "Racing on two wheels", category: "Sports" },
  { word: "VOLLEYBALL", hint: "Nepal's national sport", category: "Sports" },
  { word: "HOCKEY", hint: "Stick sport on ice or field", category: "Sports" },
  { word: "SKIING", hint: "Gliding down snowy slopes", category: "Sports" },
  { word: "ARCHERY", hint: "Sport of bow and arrow", category: "Sports" },
  { word: "GARDEN", hint: "Where flowers grow", category: "General" },
  { word: "BRIDGE", hint: "It spans a river", category: "General" },
  { word: "LIBRARY", hint: "House of books", category: "General" },
  { word: "WINDOW", hint: "Glass opening in a wall", category: "General" },
  { word: "PLANET", hint: "Earth is one", category: "General" },
  { word: "GUITAR", hint: "Six-string instrument", category: "General" },
  { word: "OCEAN", hint: "Vast body of salt water", category: "General" },
  { word: "CASTLE", hint: "Fortified palace", category: "General" },
  { word: "RIVER", hint: "Flowing body of fresh water", category: "General" },
  { word: "MOUNTAIN", hint: "Tall natural peak", category: "General" },
  { word: "DESERT", hint: "Dry sandy wilderness", category: "General" },
  { word: "ISLAND", hint: "Land surrounded by water", category: "General" },
  { word: "FOREST", hint: "Dense area of trees", category: "General" },
  { word: "MARKET", hint: "Place to buy and sell", category: "General" },
  { word: "CANDLE", hint: "Wax stick that gives light", category: "General" },
  { word: "COMPASS", hint: "It always points north", category: "General" },
];

export interface HangmanWord {
  word: string;
  hint: string;
  category: string;
}

export const HANGMAN_WORDS: HangmanWord[] = [
  { word: "EVEREST", hint: "Tallest mountain on Earth", category: "Nepal" },
  { word: "POKHARA", hint: "City of lakes", category: "Nepal" },
  { word: "BHAKTAPUR", hint: "Ancient Newar city", category: "Nepal" },
  { word: "CHITWAN", hint: "Famous national park", category: "Nepal" },
  { word: "GORKHA", hint: "Historic hill kingdom", category: "Nepal" },
  { word: "MUSTANG", hint: "Trans-Himalayan district", category: "Nepal" },
  { word: "DHALBHAT", hint: "Staple Nepali meal", category: "Nepal" },
  { word: "KUMARI", hint: "Living goddess tradition", category: "Nepal" },
  { word: "LUMBINI", hint: "Birthplace of the Buddha", category: "Nepal" },
  { word: "PATAN", hint: "City of fine arts", category: "Nepal" },
  { word: "DHARAN", hint: "Eastern hill city", category: "Nepal" },
  { word: "BUTWAL", hint: "Gateway to the hills", category: "Nepal" },
  { word: "YAK", hint: "High-mountain bovine", category: "Nepal" },
  { word: "DANPHE", hint: "Colourful national bird", category: "Nepal" },
  { word: "MOMO", hint: "Steamed dumpling", category: "Nepal" },
  { word: "SHERPA", hint: "Mountain climbing community", category: "Nepal" },
  { word: "GURKHA", hint: "Famed Nepali soldiers", category: "Nepal" },
  { word: "THAMEL", hint: "Tourist hub of Kathmandu", category: "Nepal" },
  { word: "JOMSOM", hint: "Windy town of Mustang", category: "Nepal" },
  { word: "NAMCHE", hint: "Sherpa town above Lukla", category: "Nepal" },
  { word: "LAPTOP", hint: "Portable computer", category: "Technology" },
  { word: "SERVER", hint: "Serves data over a network", category: "Technology" },
  { word: "ROUTER", hint: "Directs network traffic", category: "Technology" },
  { word: "PIXEL", hint: "Smallest screen dot", category: "Technology" },
  { word: "ALGORITHM", hint: "Step-by-step procedure", category: "Technology" },
  { word: "COMPUTER", hint: "Electronic brain", category: "Technology" },
  { word: "PYTHON", hint: "Snake-named language", category: "Technology" },
  { word: "ROBOT", hint: "Mechanical helper", category: "Technology" },
  { word: "TABLET", hint: "Flat touchscreen device", category: "Technology" },
  { word: "MODEM", hint: "It dials you online", category: "Technology" },
  { word: "PRINTER", hint: "Paper output machine", category: "Technology" },
  { word: "SCREEN", hint: "Display you stare at", category: "Technology" },
  { word: "SPEAKER", hint: "It makes sound louder", category: "Technology" },
  { word: "CAMERA", hint: "It captures photos", category: "Technology" },
  { word: "KEYBOARD", hint: "Board full of keys", category: "Technology" },
  { word: "SOFTWARE", hint: "Intangible programs", category: "Technology" },
  { word: "NEPAL", hint: "Himalayan nation", category: "Countries" },
  { word: "INDIA", hint: "Nepal's southern neighbour", category: "Countries" },
  { word: "CHINA", hint: "Nepal's northern neighbour", category: "Countries" },
  { word: "BHUTAN", hint: "Thunder-dragon kingdom", category: "Countries" },
  { word: "JAPAN", hint: "Island nation of the east", category: "Countries" },
  { word: "FRANCE", hint: "Country of the Louvre", category: "Countries" },
  { word: "ITALY", hint: "Land of Rome", category: "Countries" },
  { word: "SPAIN", hint: "Land of flamenco", category: "Countries" },
  { word: "EGYPT", hint: "Land of pharaohs", category: "Countries" },
  { word: "BRAZIL", hint: "Land of samba", category: "Countries" },
  { word: "PERU", hint: "Andean nation", category: "Countries" },
  { word: "KENYA", hint: "Safari nation", category: "Countries" },
  { word: "MEXICO", hint: "Land of the Aztecs", category: "Countries" },
  { word: "GREECE", hint: "Land of philosophers", category: "Countries" },
  { word: "THAILAND", hint: "Land of smiles", category: "Countries" },
  { word: "TURKEY", hint: "Bridge of two continents", category: "Countries" },
  { word: "TITANIC", hint: "Famous 1997 ship film", category: "Movies" },
  { word: "AVATAR", hint: "Blue aliens of Pandora", category: "Movies" },
  { word: "INCEPTION", hint: "Dream-within-a-dream film", category: "Movies" },
  { word: "JAWS", hint: "Terrifying shark film", category: "Movies" },
  { word: "FROZEN", hint: "Animated ice-queen film", category: "Movies" },
  { word: "COCO", hint: "Pixar film about music", category: "Movies" },
  { word: "DUNE", hint: "Desert-planet epic", category: "Movies" },
  { word: "ROCKY", hint: "Boxer film classic", category: "Movies" },
  { word: "ALADDIN", hint: "Magic-lamp tale", category: "Movies" },
  { word: "MULAN", hint: "Warrior heroine tale", category: "Movies" },
  { word: "SHREK", hint: "Green ogre comedy", category: "Movies" },
  { word: "GHOST", hint: "Spooky spirit", category: "Movies" },
  { word: "ALIEN", hint: "Space creature horror", category: "Movies" },
  { word: "JURASSIC", hint: "Dinosaur park films", category: "Movies" },
  { word: "CRICKET", hint: "Growing sport in Nepal", category: "Sports" },
  { word: "VOLLEYBALL", hint: "Nepal's national sport", category: "Sports" },
  { word: "FOOTBALL", hint: "Eleven-a-side game", category: "Sports" },
  { word: "TENNIS", hint: "Love-all racket game", category: "Sports" },
  { word: "CHESS", hint: "Checkmate board game", category: "Sports" },
  { word: "BOXING", hint: "Gloved fight sport", category: "Sports" },
  { word: "GOLF", hint: "Eighteen-hole game", category: "Sports" },
  { word: "RUGBY", hint: "Oval-ball game", category: "Sports" },
  { word: "KARATE", hint: "Striking martial art", category: "Sports" },
  { word: "HOCKEY", hint: "Stick-and-puck game", category: "Sports" },
  { word: "PLANET", hint: "Earth is one", category: "General" },
  { word: "OCEAN", hint: "Vast body of salt water", category: "General" },
  { word: "GARDEN", hint: "Where flowers grow", category: "General" },
  { word: "CASTLE", hint: "Fortified palace", category: "General" },
  { word: "RIVER", hint: "Flowing water", category: "General" },
  { word: "MOUNTAIN", hint: "High natural peak", category: "General" },
  { word: "DESERT", hint: "Arid land", category: "General" },
  { word: "ISLAND", hint: "Lonely landmass", category: "General" },
  { word: "FOREST", hint: "Wooded land", category: "General" },
  { word: "CANDLE", hint: "Wax light", category: "General" },
  { word: "BRIDGE", hint: "River crosser", category: "General" },
  { word: "WINDOW", hint: "Wall opening", category: "General" },
  { word: "MARKET", hint: "Trading place", category: "General" },
  { word: "WINTER", hint: "Coldest season", category: "General" },
  { word: "SUMMER", hint: "Hottest season", category: "General" },
  { word: "SPRING", hint: "Season of blooms", category: "General" },
  { word: "AUTUMN", hint: "Season of falling leaves", category: "General" },
  { word: "RAINBOW", hint: "Arch after rain", category: "General" },
  { word: "VOLCANO", hint: "Erupting mountain", category: "General" },
  { word: "MEADOW", hint: "Grassy field", category: "General" },
  { word: "VALLEY", hint: "Low land between hills", category: "General" },
  { word: "SUNSET", hint: "Day's glowing end", category: "General" },
  { word: "SUNRISE", hint: "Day's glowing start", category: "General" },
  { word: "LANTERN", hint: "Portable lamp", category: "General" },
  { word: "COMPASS", hint: "Direction finder", category: "General" },
  { word: "ANCHOR", hint: "It holds ships still", category: "General" },
  { word: "PYRAMID", hint: "Triangular tomb", category: "General" },
  { word: "THUNDER", hint: "Loud sky rumble", category: "General" },
];

const TYPING_A =
  "time people way day man thing woman life child world school state family student group country problem hand part place over such again only round morning water paper mountain river nepali himalaya kathmandu pokhara travel food music light heart dream peace cloud forest trail peak lake village market bridge stone snow sun moon star song journey summit climb prayer flag temple story night brave kind quick brown fox jumps over lazy dog practice makes perfect type fast steady rhythm focus calm mind hands dance across keys while words flow like rivers through valleys ever every after first well also play small house large great little own same think know take come made find long down side been much before line too mean old any same tell does set want air well play small end put home read hand port large spell add even land here must big high such follow act why ask men change went light kind off need house picture try again animal point mother answer grow study still learn should plant cover food sun four between state keep eye never last let thought city tree cross farm hard start might story saw left late run while press close night real life few north open seem together next white children begin got walk example ease paper group always music those both mark often letter until mile river carry science eat room friend began idea fish mountain stop once base hear horse cut sure watch color face wood main enough plain girl usual young ready above ever red list though feel talk bird soon body dog family direct pose leave song measure door product black short numeral class wind question happen complete ship area half rock order fire south problem piece told knew pass since top whole king space heard best hour better during hundred five remember step early hold west ground interest reach fast verb sing listen six table travel less morning ten simple several vowel toward war lay against pattern slow center love person money serve appear road rain rule govern pull cold notice voice unit power town fine certain fly fall lead cry dark machine note wait plan figure star box noun field rest correct able pound done beauty drive stood contain front teach week final gave green oh quick develop ocean warm free minute strong special mind behind clear tail produce fact street inch lot nothing course stay wheel full force blue object decide surface deep moon island foot yet busy test record boat common gold possible plane stead dry wonder laugh thousand ago ran check game shape equate hot miss brought heat snow tire bring yes distant fill east paint language among grand ball yet wave drop heart am present heavy dance engine position arm wide sail material size vary settle speak weight general ice matter circle pair include divide syllable felt perhaps pick sudden count square reason length represent art subject region energy hunt probable bed brother egg ride cell believe fraction forest sit race window store summer train sleep prove lone leg exercise wall catch mount wish sky board joy winter sat written wild instrument kept glass grass cow job edge sign visit past soft fun bright gas weather month million bear finish happy hope flower clothe strange gone jump baby eight village meet root buy raise solve metal whether push seven paragraph third shall held hair describe cook floor either result burn hill safe cat century consider type law bit coast copy phrase silent tall sand soil roll temperature finger industry value fight lie beat excite natural view sense ear else quite broke case middle kill son lake moment scale loud spring observe girl row moment forest parade";

const TYPING_B =
  "everest annapurna lumbini chitwan gorkha mustang thakali momo dalbhat himalaya sherpa pokhara patan bhaktapur terai hill valley trail basecamp teahouse rhododendron yak yeti monastery stupa temple festival dashain tihar holi teej chhath mela bazaar rupee bhat masala chiya aachar selroti yomari bara dhido gundruk thukpa lapsi aamp mango litchi papaya banana coconut lemon ginger garlic onion potato tomato rice wheat maize millet barley lentil bean pea carrot cabbage mushroom apple orange grape fruit sweet salt sugar spice warm cold fresh taste cook bake roast fry boil steam share serve plate bowl cup glass table chair house home school office shop road street bridge river lake pond ocean beach coast desert forest garden park farm field crop seed leaf root branch trunk bark petal bloom spring summer autumn winter rain snow hail storm wind breeze cloud fog mist dew frost ice thunder lightning rainbow sunshine sunset sunrise dawn dusk noon midnight morning evening night today tomorrow yesterday week month year season century moment minute hour second clock watch calendar date birth death life love hope faith joy peace smile laugh song dance music drum flute bell song story poem tale myth legend hero brave bold kind wise smart clever funny happy glad merry jolly proud humble quiet loud soft hard easy tough rough smooth sharp blunt sweet sour bitter fresh stale clean dirty neat tidy messy clear cloudy bright dark dim glow shine sparkle glitter shimmer flash gleam beam ray light lamp torch lantern candle bulb fire flame coal ash smoke coal ember heat warm cool cold chill frost freeze melt boil steam bake roast grill toast fry cook eat drink taste chew swallow bite sip supper lunch dinner breakfast feast snack meal dish plate feast treat sweet candy cake pie bread roll bun loaf toast crust crumb slice chunk piece part whole half quarter full empty heavy light large small big tiny huge vast wide narrow long short tall high low deep shallow thick thin fat slim broad tight loose fast slow quick rapid swift brisk idle still calm quiet loud noisy busy free easy hard work job task chore duty shift craft skill trade art music sport game play fun joke laugh smile grin cheer happy hobby pastime leisure rest nap sleep dream wake rise sit stand walk run jog sprint dash race chase flee climb crawl swim dive float sail row paddle float drift glide fly soar hover float sink swim splash spray sprinkle shower rain pour stream flow gush drip drop ooze seep leak spill splash stain spot mark dot point line trace draw paint sketch color shade tint hue dye print stamp carve mold shape form build make craft create invent design plan scheme plot dream think ponder wonder muse guess judge deem feel sense touch taste smell hear see look watch view gaze stare glance peek peer spy spot find lose seek hunt chase track trail trace scent sniff sniffle sneeze cough choke gag retch choke gasp pant sigh yawn snore sleep nap doze drowse rest relax ease calm soothe comfort cheer gladden please amuse tease taunt mock jeer cheer applaud praise laud hail greet meet greet welcome host guest hostess host invite visit call phone text mail write pen ink paper note memo note diary journal log book novel tale story fable myth epic saga poem verse rhyme song hymn chant choir chorus band troop team crew gang squad party group crowd throng horde flock herd pack drove swarm school shoal pod pride troop colony nest hive den burrow lair nest roost perch";

export const TYPING_WORDS: string[] = [
  ...new Set(`${TYPING_A} ${TYPING_B}`.split(/\s+/).filter(Boolean)),
];

export const TYPING_QUOTES: string[] = [
  "The mountains of Nepal remind us that great heights are reached one steady step at a time.",
  "Typing fast is a rhythm sport: relax your shoulders, trust your fingers, and keep your eyes ahead.",
  "Pokhara mornings are calm and golden, with boats drifting slow across the glassy lake.",
  "Consistency beats bursts. Smooth keystrokes today become effortless speed tomorrow.",
  "Every expert was once a beginner who refused to stop practicing their craft daily.",
  "The trail to the summit is long, but each small step forward is a quiet victory.",
  "Focus on accuracy first and speed will follow like a shadow that never leaves.",
  "A calm mind types faster than hurried fingers that stumble over every word.",
  "Rivers carve valleys not through force but through steady patient persistence.",
  "The best time to practice was yesterday, and the next best time is right now.",
  "Great typists do not watch their hands; they watch the road ahead of them.",
  "Small daily habits quietly compound into skills that look like magic later.",
  "Mistakes are teachers in disguise, so learn from each one and keep going.",
  "Patience turns rough drafts into polished work and slow hands into fast ones.",
  "Even Everest is climbed one careful footstep after another, never in a leap.",
  "Rhythm matters more than rush; find your beat and let your fingers dance.",
  "Clear goals and steady effort will carry you further than talent alone.",
  "The keyboard rewards those who return to it day after day without fail.",
  "Slow is smooth and smooth becomes fast with enough patient practice.",
  "A journey of a thousand words begins with a single confident keystroke.",
];

export interface QuizQuestion {
  id: string;
  category: string;
  type: "mcq" | "tf";
  question: string;
  choices: string[];
  answer: number; // index into choices
  explain?: string;
}

// Stable, low-risk general facts only. 104 questions, 13 per category.
export const QUIZ_QUESTIONS: QuizQuestion[] = [
  { id: "s1", category: "Science", type: "mcq", question: "How many days does Earth take to orbit the Sun?", choices: ["265", "365", "385", "400"], answer: 1 },
  { id: "s2", category: "Science", type: "mcq", question: "What is H2O commonly known as?", choices: ["Salt", "Water", "Oxygen", "Hydrogen"], answer: 1 },
  { id: "s3", category: "Science", type: "tf", question: "Sound travels faster than light.", choices: ["True", "False"], answer: 1 },
  { id: "s4", category: "Science", type: "mcq", question: "Which planet is known as the Red Planet?", choices: ["Venus", "Mars", "Jupiter", "Mercury"], answer: 1 },
  { id: "s5", category: "Science", type: "mcq", question: "How many legs does a spider have?", choices: ["6", "8", "10", "12"], answer: 1 },
  { id: "s6", category: "Science", type: "mcq", question: "At sea level, water boils at about…", choices: ["90 degrees Celsius", "100 degrees Celsius", "110 degrees Celsius", "120 degrees Celsius"], answer: 1 },
  { id: "s7", category: "Science", type: "mcq", question: "Which gas do plants absorb for photosynthesis?", choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], answer: 2 },
  { id: "s8", category: "Science", type: "mcq", question: "Which is the largest planet in our solar system?", choices: ["Earth", "Saturn", "Jupiter", "Neptune"], answer: 2 },
  { id: "s9", category: "Science", type: "mcq", question: "How many chambers does the human heart have?", choices: ["2", "3", "4", "5"], answer: 2 },
  { id: "s10", category: "Science", type: "mcq", question: "Water freezes at about…", choices: ["0 degrees Celsius", "10 degrees Celsius", "32 degrees Celsius", "100 degrees Celsius"], answer: 0 },
  { id: "s11", category: "Science", type: "mcq", question: "Which star is nearest to Earth?", choices: ["Polaris", "Sirius", "The Sun", "Vega"], answer: 2 },
  { id: "s12", category: "Science", type: "mcq", question: "About how many bones are in the adult human body?", choices: ["106", "156", "206", "306"], answer: 2 },
  { id: "s13", category: "Science", type: "mcq", question: "Who is famous for describing gravity after watching an apple fall?", choices: ["Einstein", "Galileo", "Newton", "Darwin"], answer: 2 },
  { id: "t1", category: "Technology", type: "mcq", question: "What does CPU stand for?", choices: ["Central Processing Unit", "Computer Personal Utility", "Central Program Utility", "Core Processing Utility"], answer: 0 },
  { id: "t2", category: "Technology", type: "mcq", question: "Which company created the iPhone?", choices: ["Samsung", "Google", "Apple", "Nokia"], answer: 2 },
  { id: "t3", category: "Technology", type: "tf", question: "HTML is a programming language.", choices: ["True", "False"], answer: 1, explain: "HTML is a markup language." },
  { id: "t4", category: "Technology", type: "mcq", question: "What does Wi-Fi most commonly provide?", choices: ["Wired printing", "Wireless networking", "Satellite TV", "Battery charging"], answer: 1 },
  { id: "t5", category: "Technology", type: "mcq", question: "Which storage unit is the largest?", choices: ["Megabyte", "Gigabyte", "Terabyte", "Kilobyte"], answer: 2 },
  { id: "t6", category: "Technology", type: "mcq", question: "What does USB stand for?", choices: ["Universal Serial Bus", "United System Board", "Ultra Speed Bandwidth", "Unified Server Backup"], answer: 0 },
  { id: "t7", category: "Technology", type: "mcq", question: "What does PDF stand for?", choices: ["Printed Document File", "Portable Document Format", "Public Data Folder", "Programmed Disk File"], answer: 1 },
  { id: "t8", category: "Technology", type: "mcq", question: "Which company makes the Windows operating system?", choices: ["Apple", "Microsoft", "Intel", "Adobe"], answer: 1 },
  { id: "t9", category: "Technology", type: "mcq", question: "How many bits are in one byte?", choices: ["2", "4", "8", "16"], answer: 2 },
  { id: "t10", category: "Technology", type: "mcq", question: "Email stands for…", choices: ["Express mail", "Electronic mail", "Emergency mail", "External mail"], answer: 1 },
  { id: "t11", category: "Technology", type: "mcq", question: "Which of these is an input device?", choices: ["Monitor", "Printer", "Mouse", "Speaker"], answer: 2 },
  { id: "t12", category: "Technology", type: "mcq", question: "What is a keyboard mainly used for?", choices: ["Typing text", "Printing pages", "Playing sound", "Showing video"], answer: 0 },
  { id: "t13", category: "Technology", type: "mcq", question: "What does the Delete key usually do?", choices: ["Saves a file", "Removes text forward", "Opens a menu", "Shuts down"], answer: 1 },
  { id: "w1", category: "World", type: "mcq", question: "Which is the largest ocean on Earth?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
  { id: "w2", category: "World", type: "mcq", question: "How many continents are there?", choices: ["5", "6", "7", "8"], answer: 2 },
  { id: "w3", category: "World", type: "tf", question: "The Sahara is the world's largest hot desert.", choices: ["True", "False"], answer: 0 },
  { id: "w4", category: "World", type: "mcq", question: "Which country has the largest population?", choices: ["USA", "Indonesia", "India", "Brazil"], answer: 2 },
  { id: "w5", category: "World", type: "mcq", question: "Which is the smallest continent?", choices: ["Europe", "Antarctica", "Australia", "South America"], answer: 2 },
  { id: "w6", category: "World", type: "mcq", question: "Which place is both a country and a continent?", choices: ["Greenland", "Australia", "Madagascar", "Antarctica"], answer: 1 },
  { id: "w7", category: "World", type: "mcq", question: "What is the capital of the USA?", choices: ["New York", "Los Angeles", "Washington, D.C.", "Chicago"], answer: 2 },
  { id: "w8", category: "World", type: "mcq", question: "What is the currency of Japan?", choices: ["Won", "Yuan", "Yen", "Ringgit"], answer: 2 },
  { id: "w9", category: "World", type: "mcq", question: "Paper is widely believed to have been invented in…", choices: ["Egypt", "Greece", "China", "Rome"], answer: 2 },
  { id: "w10", category: "World", type: "mcq", question: "Which country is called the land of the rising sun?", choices: ["China", "Japan", "Thailand", "Korea"], answer: 1 },
  { id: "w11", category: "World", type: "mcq", question: "The pyramids of Giza are in…", choices: ["Mexico", "Sudan", "Egypt", "Peru"], answer: 2 },
  { id: "w12", category: "World", type: "mcq", question: "The Eiffel Tower is in…", choices: ["London", "Paris", "Rome", "Berlin"], answer: 1 },
  { id: "w13", category: "World", type: "mcq", question: "Which is the largest continent?", choices: ["Africa", "Asia", "Europe", "North America"], answer: 1 },
  { id: "h1", category: "History", type: "mcq", question: "In which year did humans first land on the Moon?", choices: ["1959", "1969", "1979", "1989"], answer: 1 },
  { id: "h2", category: "History", type: "tf", question: "The Great Wall is in China.", choices: ["True", "False"], answer: 0 },
  { id: "h3", category: "History", type: "mcq", question: "Which ancient civilization built the pyramids of Giza?", choices: ["Romans", "Greeks", "Egyptians", "Mayans"], answer: 2 },
  { id: "h4", category: "History", type: "mcq", question: "In which year did the First World War begin?", choices: ["1905", "1914", "1921", "1939"], answer: 1 },
  { id: "h5", category: "History", type: "mcq", question: "In which year did the Berlin Wall fall?", choices: ["1979", "1985", "1989", "1995"], answer: 2 },
  { id: "h6", category: "History", type: "mcq", question: "Who was the first president of the USA?", choices: ["Lincoln", "Jefferson", "Washington", "Adams"], answer: 2 },
  { id: "h7", category: "History", type: "mcq", question: "The ancient Olympic Games were held in…", choices: ["Rome", "Greece", "Egypt", "Spain"], answer: 1 },
  { id: "h8", category: "History", type: "mcq", question: "Who is credited with inventing the printing press?", choices: ["Da Vinci", "Gutenberg", "Edison", "Bell"], answer: 1 },
  { id: "h9", category: "History", type: "mcq", question: "In which year did the Titanic sink?", choices: ["1905", "1912", "1920", "1931"], answer: 1 },
  { id: "h10", category: "History", type: "mcq", question: "Who painted the Mona Lisa?", choices: ["Van Gogh", "Picasso", "Da Vinci", "Rembrandt"], answer: 2 },
  { id: "h11", category: "History", type: "mcq", question: "What language did the ancient Romans speak?", choices: ["Greek", "Latin", "Arabic", "Sanskrit"], answer: 1 },
  { id: "h12", category: "History", type: "mcq", question: "What is the picture-writing of ancient Egypt called?", choices: ["Cuneiform", "Hieroglyphs", "Runes", "Calligraphy"], answer: 1 },
  { id: "h13", category: "History", type: "mcq", question: "Who built the Taj Mahal?", choices: ["Akbar", "Shah Jahan", "Ashoka", "Babur"], answer: 1 },
  { id: "e1", category: "Entertainment", type: "mcq", question: "How many players are on a football (soccer) team on the field?", choices: ["9", "10", "11", "12"], answer: 2 },
  { id: "e2", category: "Entertainment", type: "tf", question: "Chess is played on an 8x8 board.", choices: ["True", "False"], answer: 0 },
  { id: "e3", category: "Entertainment", type: "mcq", question: "How many strings does a standard guitar have?", choices: ["4", "5", "6", "7"], answer: 2 },
  { id: "e4", category: "Entertainment", type: "mcq", question: "Which film features the ice queen Elsa?", choices: ["Moana", "Frozen", "Tangled", "Brave"], answer: 1 },
  { id: "e5", category: "Entertainment", type: "mcq", question: "Who created Mickey Mouse?", choices: ["Walt Disney", "Pixar", "Warner", "Hanna-Barbera"], answer: 0 },
  { id: "e6", category: "Entertainment", type: "mcq", question: "How many players are on a cricket team?", choices: ["9", "10", "11", "15"], answer: 2 },
  { id: "e7", category: "Entertainment", type: "mcq", question: "How often are the Olympic Games held?", choices: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], answer: 2 },
  { id: "e8", category: "Entertainment", type: "mcq", question: "Which instrument has 88 keys?", choices: ["Guitar", "Piano", "Violin", "Flute"], answer: 1 },
  { id: "e9", category: "Entertainment", type: "mcq", question: "What is Spider-Man's real name?", choices: ["Clark Kent", "Bruce Wayne", "Peter Parker", "Tony Stark"], answer: 2 },
  { id: "e10", category: "Entertainment", type: "mcq", question: "Hobbits appear in which fantasy saga?", choices: ["Harry Potter", "Narnia", "Lord of the Rings", "Star Wars"], answer: 2 },
  { id: "e11", category: "Entertainment", type: "mcq", question: "What does Pac-Man eat in the maze?", choices: ["Ghosts", "Dots", "Keys", "Stars"], answer: 1 },
  { id: "e12", category: "Entertainment", type: "mcq", question: "In which game would you meet a Creeper?", choices: ["Fortnite", "Minecraft", "Roblox", "Mario"], answer: 1 },
  { id: "e13", category: "Entertainment", type: "mcq", question: "Who is Mario's brother?", choices: ["Wario", "Luigi", "Yoshi", "Toad"], answer: 1 },
  { id: "sp1", category: "Sports", type: "mcq", question: "In cricket, how many balls are in one over?", choices: ["5", "6", "8", "10"], answer: 1 },
  { id: "sp2", category: "Sports", type: "mcq", question: "Which sport uses a shuttlecock?", choices: ["Tennis", "Badminton", "Squash", "Table tennis"], answer: 1 },
  { id: "sp3", category: "Sports", type: "mcq", question: "How often is the FIFA World Cup held?", choices: ["Every year", "Every 2 years", "Every 3 years", "Every 4 years"], answer: 3 },
  { id: "sp4", category: "Sports", type: "mcq", question: "How many Grand Slam tennis tournaments are held each year?", choices: ["2", "3", "4", "5"], answer: 2 },
  { id: "sp5", category: "Sports", type: "mcq", question: "About how long is a marathon?", choices: ["10 km", "21 km", "42 km", "100 km"], answer: 2 },
  { id: "sp6", category: "Sports", type: "mcq", question: "How many players per basketball team are on the court?", choices: ["5", "6", "7", "11"], answer: 0 },
  { id: "sp7", category: "Sports", type: "mcq", question: "Which sport uses a puck?", choices: ["Field hockey", "Ice hockey", "Lacrosse", "Polo"], answer: 1 },
  { id: "sp8", category: "Sports", type: "mcq", question: "Who holds the men's 100m world record?", choices: ["Carl Lewis", "Usain Bolt", "Tyson Gay", "Justin Gatlin"], answer: 1 },
  { id: "sp9", category: "Sports", type: "mcq", question: "How many chess pieces does each player start with?", choices: ["12", "14", "16", "20"], answer: 2 },
  { id: "sp10", category: "Sports", type: "mcq", question: "Golf is played on a…", choices: ["Court", "Course", "Rink", "Track"], answer: 1 },
  { id: "sp11", category: "Sports", type: "mcq", question: "What shape is a boxing ring?", choices: ["Circle", "Triangle", "Square", "Octagon"], answer: 2 },
  { id: "sp12", category: "Sports", type: "mcq", question: "How many hits per side are allowed in volleyball?", choices: ["2", "3", "4", "Unlimited"], answer: 1 },
  { id: "sp13", category: "Sports", type: "mcq", question: "A table-tennis game is commonly played to how many points?", choices: ["7", "9", "11", "21"], answer: 2 },
  { id: "g1", category: "Geography", type: "mcq", question: "Which is the longest river in the world?", choices: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: 1, explain: "Commonly cited; Amazon is a close contender by some measures." },
  { id: "g2", category: "Geography", type: "tf", question: "Mount Everest lies in the Himalayas.", choices: ["True", "False"], answer: 0 },
  { id: "g3", category: "Geography", type: "mcq", question: "Which ocean lies between Africa and Australia?", choices: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 1 },
  { id: "g4", category: "Geography", type: "mcq", question: "The Sahara desert is mostly on which continent?", choices: ["Asia", "Africa", "Australia", "South America"], answer: 1 },
  { id: "g5", category: "Geography", type: "mcq", question: "Which country is famous for having the most natural lakes?", choices: ["Russia", "Canada", "Finland", "USA"], answer: 1 },
  { id: "g6", category: "Geography", type: "mcq", question: "Most of the Amazon rainforest is in…", choices: ["Peru", "Colombia", "Brazil", "Venezuela"], answer: 2 },
  { id: "g7", category: "Geography", type: "mcq", question: "Which imaginary line divides Earth into northern and southern halves?", choices: ["Prime Meridian", "Equator", "Tropic of Cancer", "Arctic Circle"], answer: 1 },
  { id: "g8", category: "Geography", type: "mcq", question: "About how tall is Mount Everest?", choices: ["8,000 m", "8,500 m", "8,849 m", "9,200 m"], answer: 2 },
  { id: "g9", category: "Geography", type: "mcq", question: "Which of these is an island country?", choices: ["Nepal", "Japan", "Switzerland", "Mongolia"], answer: 1 },
  { id: "g10", category: "Geography", type: "mcq", question: "The Dead Sea is famous because people can…", choices: ["Freeze in it", "Float in it easily", "Drink from it", "Surf on it"], answer: 1 },
  { id: "g11", category: "Geography", type: "mcq", question: "Egypt is mostly on which continent?", choices: ["Asia", "Africa", "Europe", "Australia"], answer: 1 },
  { id: "g12", category: "Geography", type: "mcq", question: "Which is the deepest ocean on Earth?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
  { id: "g13", category: "Geography", type: "mcq", question: "Which US state is a chain of islands?", choices: ["Alaska", "Florida", "Hawaii", "Texas"], answer: 2 },
  { id: "gk1", category: "General Knowledge", type: "mcq", question: "How many days are in a leap year?", choices: ["365", "366", "364", "367"], answer: 1 },
  { id: "gk2", category: "General Knowledge", type: "mcq", question: "Which vitamin does sunlight help our skin make?", choices: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], answer: 2 },
  { id: "gk3", category: "General Knowledge", type: "tf", question: "A decade lasts 10 years.", choices: ["True", "False"], answer: 0 },
  { id: "gk4", category: "General Knowledge", type: "mcq", question: "How many colors are in a rainbow?", choices: ["5", "6", "7", "8"], answer: 2 },
  { id: "gk5", category: "General Knowledge", type: "mcq", question: "How many sides does a hexagon have?", choices: ["5", "6", "7", "8"], answer: 1 },
  { id: "gk6", category: "General Knowledge", type: "mcq", question: "How many minutes are in one hour?", choices: ["30", "60", "90", "100"], answer: 1 },
  { id: "gk7", category: "General Knowledge", type: "mcq", question: "Which months have at least 28 days?", choices: ["February only", "January only", "All of them", "None of them"], answer: 2 },
  { id: "gk8", category: "General Knowledge", type: "mcq", question: "How many lights does a standard traffic signal have?", choices: ["2", "3", "4", "5"], answer: 1 },
  { id: "gk9", category: "General Knowledge", type: "mcq", question: "Which shape has exactly three sides?", choices: ["Square", "Triangle", "Pentagon", "Circle"], answer: 1 },
  { id: "gk10", category: "General Knowledge", type: "mcq", question: "Which is heavier: 1 kg of steel or 1 kg of feathers?", choices: ["Steel", "Feathers", "Neither, they weigh the same", "Impossible to say"], answer: 2 },
  { id: "gk11", category: "General Knowledge", type: "mcq", question: "How many letters are in the English alphabet?", choices: ["24", "25", "26", "28"], answer: 2 },
  { id: "gk12", category: "General Knowledge", type: "mcq", question: "In which direction does the sun rise?", choices: ["North", "South", "East", "West"], answer: 2 },
  { id: "gk13", category: "General Knowledge", type: "mcq", question: "What do honeybees make?", choices: ["Wax only", "Honey", "Silk", "Milk"], answer: 1 },
];

export interface NepalQuestion {
  id: string;
  category: string;
  type: "mcq" | "tf";
  question: string;
  choices: string[];
  answer: number;
}

// Conservative, stable facts about Nepal. 108 questions.
export const NEPAL_QUESTIONS: NepalQuestion[] = [
  { id: "n1", category: "General", type: "mcq", question: "What is the capital city of Nepal?", choices: ["Pokhara", "Kathmandu", "Biratnagar", "Nepalgunj"], answer: 1 },
  { id: "n2", category: "General", type: "mcq", question: "What is the currency of Nepal?", choices: ["Taka", "Rupee", "Rupiah", "Kyat"], answer: 1 },
  { id: "n3", category: "General", type: "tf", question: "Nepal is a landlocked country.", choices: ["True", "False"], answer: 0 },
  { id: "n4", category: "General", type: "mcq", question: "Which two countries border Nepal?", choices: ["India and China", "India and Bangladesh", "China and Bhutan", "India and Myanmar"], answer: 0 },
  { id: "n5", category: "General", type: "tf", question: "Nepal was never colonized by a foreign power.", choices: ["True", "False"], answer: 0 },
  { id: "n6", category: "General", type: "mcq", question: "What is Nepal's system of government?", choices: ["Monarchy", "Federal democratic republic", "One-party state", "Military rule"], answer: 1 },
  { id: "n7", category: "General", type: "mcq", question: "What is Nepal's unusual time zone?", choices: ["UTC+5:30", "UTC+5:45", "UTC+6:00", "UTC+5:00"], answer: 1 },
  { id: "n8", category: "General", type: "mcq", question: "What is the official language of Nepal?", choices: ["Nepali", "Hindi", "Newari", "English"], answer: 0 },
  { id: "n9", category: "General", type: "mcq", question: "What is Nepal's national anthem?", choices: ["Sayaun Thunga Phulka", "Jana Gana Mana", "Qaumi Tarana", "Kantipur Anthem"], answer: 0 },
  { id: "n10", category: "General", type: "mcq", question: "Nepal's national flag is…", choices: ["Rectangular", "Double-pennant shaped", "Circular", "Triangular"], answer: 1 },
  { id: "n11", category: "General", type: "mcq", question: "Which animal is revered as Nepal's national animal?", choices: ["Cow", "Tiger", "Elephant", "Yak"], answer: 0 },
  { id: "n12", category: "General", type: "mcq", question: "What is Nepal's national bird?", choices: ["Danphe", "Sparrow", "Eagle", "Parrot"], answer: 0 },
  { id: "n13", category: "General", type: "mcq", question: "What is Nepal's national flower?", choices: ["Lotus", "Rhododendron", "Sunflower", "Marigold"], answer: 1 },
  { id: "n14", category: "General", type: "mcq", question: "Nepal's national sport is…", choices: ["Football", "Cricket", "Volleyball", "Kabaddi"], answer: 2 },
  { id: "n15", category: "General", type: "mcq", question: "About how many people live in Nepal?", choices: ["10 million", "30 million", "60 million", "100 million"], answer: 1 },
  { id: "n16", category: "General", type: "mcq", question: "The word Himalaya is often translated as…", choices: ["Abode of snow", "Land of rivers", "Roof of Asia", "Snowy desert"], answer: 0 },
  { id: "n17", category: "Geography", type: "mcq", question: "Which mountain is the tallest in the world and lies in Nepal?", choices: ["K2", "Kanchenjunga", "Mount Everest", "Makalu"], answer: 2 },
  { id: "n18", category: "Geography", type: "mcq", question: "About how tall is Mount Everest?", choices: ["8,000 m", "8,495 m", "8,849 m", "9,100 m"], answer: 2 },
  { id: "n19", category: "Geography", type: "tf", question: "Mount Everest lies in the Himalayas.", choices: ["True", "False"], answer: 0 },
  { id: "n20", category: "Geography", type: "mcq", question: "Which is NOT one of Nepal's three ecological belts?", choices: ["Terai", "Hill", "Mountain", "Desert"], answer: 3 },
  { id: "n21", category: "Geography", type: "tf", question: "The Terai is the flat southern plain of Nepal.", choices: ["True", "False"], answer: 0 },
  { id: "n22", category: "Geography", type: "mcq", question: "How many of the world's 14 eight-thousanders are in Nepal?", choices: ["6", "8", "10", "12"], answer: 1 },
  { id: "n23", category: "Geography", type: "mcq", question: "Kanchenjunga is the world's … highest mountain.", choices: ["2nd", "3rd", "4th", "5th"], answer: 1 },
  { id: "n24", category: "Geography", type: "mcq", question: "Which is commonly cited as Nepal's longest river?", choices: ["Koshi", "Gandaki", "Karnali", "Bagmati"], answer: 2 },
  { id: "n25", category: "Geography", type: "mcq", question: "Which is the largest lake of Nepal?", choices: ["Phewa", "Rara", "Begnas", "Tilicho"], answer: 1 },
  { id: "n26", category: "Geography", type: "tf", question: "The Mechi river marks part of Nepal's eastern border.", choices: ["True", "False"], answer: 0 },
  { id: "n27", category: "Geography", type: "tf", question: "The Mahakali river marks part of Nepal's western border.", choices: ["True", "False"], answer: 0 },
  { id: "n28", category: "Geography", type: "mcq", question: "Which lake is famous as a high-altitude lake?", choices: ["Phewa", "Tilicho", "Begnas", "Rupa"], answer: 1 },
  { id: "n29", category: "Geography", type: "tf", question: "The Annapurna range lies in Nepal.", choices: ["True", "False"], answer: 0 },
  { id: "n30", category: "Geography", type: "mcq", question: "Which was Nepal's first national park?", choices: ["Sagarmatha", "Chitwan", "Langtang", "Bardia"], answer: 1 },
  { id: "n31", category: "Geography", type: "mcq", question: "Sagarmatha National Park protects the region around…", choices: ["Mount Everest", "Chitwan", "Pokhara", "Mustang"], answer: 0 },
  { id: "n32", category: "Geography", type: "tf", question: "Gosaikunda is a sacred alpine lake in Nepal.", choices: ["True", "False"], answer: 0 },
  { id: "n33", category: "Provinces", type: "mcq", question: "How many provinces does Nepal have?", choices: ["5", "6", "7", "9"], answer: 2 },
  { id: "n34", category: "Provinces", type: "mcq", question: "Which province contains Kathmandu?", choices: ["Gandaki", "Bagmati", "Lumbini", "Koshi"], answer: 1 },
  { id: "n35", category: "Provinces", type: "mcq", question: "Pokhara is the capital of which province?", choices: ["Gandaki", "Karnali", "Sudurpashchim", "Madhesh"], answer: 0 },
  { id: "n36", category: "Provinces", type: "mcq", question: "Which is Nepal's easternmost province?", choices: ["Koshi", "Bagmati", "Gandaki", "Karnali"], answer: 0 },
  { id: "n37", category: "Provinces", type: "mcq", question: "Which city is the capital of Koshi province?", choices: ["Biratnagar", "Dharan", "Itahari", "Damak"], answer: 0 },
  { id: "n38", category: "Provinces", type: "mcq", question: "Which city is the capital of Madhesh province?", choices: ["Birgunj", "Lahan", "Janakpur", "Rajbiraj"], answer: 2 },
  { id: "n39", category: "Provinces", type: "mcq", question: "Which city is the capital of Bagmati province?", choices: ["Kathmandu", "Hetauda", "Bhaktapur", "Bharatpur"], answer: 1 },
  { id: "n40", category: "Provinces", type: "mcq", question: "Deukhuri is the capital of which province?", choices: ["Butwal", "Lumbini", "Gandaki", "Karnali"], answer: 1 },
  { id: "n41", category: "Provinces", type: "mcq", question: "Which city is the capital of Karnali province?", choices: ["Jumla", "Birendranagar", "Dailekh", "Jajarkot"], answer: 1 },
  { id: "n42", category: "Provinces", type: "mcq", question: "Which is the largest city of Sudurpashchim province?", choices: ["Dhangadhi", "Mahendranagar", "Tikapur", "Dadeldhura"], answer: 0 },
  { id: "n43", category: "Provinces", type: "mcq", question: "Mustang district lies in which province?", choices: ["Gandaki", "Karnali", "Lumbini", "Bagmati"], answer: 0 },
  { id: "n44", category: "Provinces", type: "mcq", question: "Chitwan district lies in which province?", choices: ["Madhesh", "Bagmati", "Gandaki", "Lumbini"], answer: 1 },
  { id: "n45", category: "Provinces", type: "mcq", question: "Solukhumbu, home of Everest, lies in which province?", choices: ["Koshi", "Bagmati", "Gandaki", "Karnali"], answer: 0 },
  { id: "n46", category: "Provinces", type: "mcq", question: "Kaski district, home of Pokhara, lies in…", choices: ["Bagmati", "Gandaki", "Lumbini", "Koshi"], answer: 1 },
  { id: "n47", category: "Provinces", type: "mcq", question: "Rupandehi district lies in which province?", choices: ["Lumbini", "Gandaki", "Karnali", "Sudurpashchim"], answer: 0 },
  { id: "n48", category: "Provinces", type: "mcq", question: "Jhapa district lies in which province?", choices: ["Madhesh", "Bagmati", "Koshi", "Gandaki"], answer: 2 },
  { id: "n49", category: "Districts", type: "mcq", question: "How many districts does Nepal have?", choices: ["75", "76", "77", "78"], answer: 2 },
  { id: "n50", category: "Districts", type: "mcq", question: "Which is the largest district of Nepal by area?", choices: ["Dolpa", "Humla", "Mustang", "Taplejung"], answer: 0 },
  { id: "n51", category: "Districts", type: "mcq", question: "Which is the smallest district of Nepal by area?", choices: ["Kathmandu", "Lalitpur", "Bhaktapur", "Kaski"], answer: 2 },
  { id: "n52", category: "Districts", type: "mcq", question: "Which district has the largest population?", choices: ["Kaski", "Kathmandu", "Morang", "Jhapa"], answer: 1 },
  { id: "n53", category: "Districts", type: "mcq", question: "Kathmandu Valley contains which three historic cities?", choices: ["Kathmandu, Lalitpur, Bhaktapur", "Pokhara, Chitwan, Butwal", "Dharan, Itahari, Biratnagar", "Nepalgunj, Dhangadhi, Mahendranagar"], answer: 0 },
  { id: "n54", category: "Districts", type: "mcq", question: "Mustang district is best described as…", choices: ["A Terai plain", "A trans-Himalayan rain-shadow region", "A coastal zone", "A desert island"], answer: 1 },
  { id: "n55", category: "Districts", type: "mcq", question: "Rara Lake lies in which district?", choices: ["Mugu", "Jumla", "Dolpa", "Humla"], answer: 0 },
  { id: "n56", category: "Districts", type: "mcq", question: "Kanchenjunga lies mainly in which district?", choices: ["Taplejung", "Sankhuwasabha", "Solukhumbu", "Dolpa"], answer: 0 },
  { id: "n57", category: "Districts", type: "mcq", question: "Which district is famous for tea gardens?", choices: ["Ilam", "Jhapa", "Panchthar", "Dhankuta"], answer: 0 },
  { id: "n58", category: "Districts", type: "mcq", question: "The Langtang valley lies mainly in which district?", choices: ["Rasuwa", "Nuwakot", "Dhading", "Sindhupalchok"], answer: 0 },
  { id: "n59", category: "Districts", type: "mcq", question: "The Tilaurakot archaeological site is in which district?", choices: ["Kapilvastu", "Rupandehi", "Dang", "Banke"], answer: 0 },
  { id: "n60", category: "Districts", type: "mcq", question: "Tansen town is in which district?", choices: ["Palpa", "Gulmi", "Syangja", "Arghakhanchi"], answer: 0 },
  { id: "n61", category: "Districts", type: "mcq", question: "Janakpur lies in which district?", choices: ["Dhanusha", "Mahottari", "Siraha", "Sarlahi"], answer: 0 },
  { id: "n62", category: "Districts", type: "mcq", question: "Dhangadhi lies in which district?", choices: ["Kailali", "Kanchanpur", "Bardiya", "Banke"], answer: 0 },
  { id: "n63", category: "Districts", type: "mcq", question: "Nepalgunj lies in which district?", choices: ["Banke", "Bardiya", "Dang", "Kailali"], answer: 0 },
  { id: "n64", category: "Districts", type: "mcq", question: "Dharan lies in which district?", choices: ["Sunsari", "Morang", "Jhapa", "Saptari"], answer: 0 },
  { id: "n65", category: "Cities", type: "mcq", question: "Which city is famous for Phewa Lake?", choices: ["Pokhara", "Dharan", "Butwal", "Hetauda"], answer: 0 },
  { id: "n66", category: "Cities", type: "mcq", question: "Biratnagar is an important city in which region?", choices: ["Eastern Terai", "Far-western hills", "High Himalayas", "Kathmandu Valley"], answer: 0 },
  { id: "n67", category: "Cities", type: "mcq", question: "Birgunj is best known as…", choices: ["A lakeside resort", "A trade gateway on the Indian border", "A hill station", "A mountain base"], answer: 1 },
  { id: "n68", category: "Cities", type: "mcq", question: "Nepalgunj is an important city in…", choices: ["The eastern Terai", "The Kathmandu Valley", "The western Terai", "The high Himalayas"], answer: 2 },
  { id: "n69", category: "Cities", type: "mcq", question: "Dharan is a major city in which part of Nepal?", choices: ["The far-west", "The eastern region", "The Kathmandu Valley", "Mustang"], answer: 1 },
  { id: "n70", category: "Cities", type: "mcq", question: "Hetauda is the capital of…", choices: ["Madhesh province", "Bagmati province", "Gandaki province", "Koshi province"], answer: 1 },
  { id: "n71", category: "Cities", type: "mcq", question: "Butwal is often called the gateway to…", choices: ["The eastern Terai", "The western hills", "Tibet", "India"], answer: 1 },
  { id: "n72", category: "Cities", type: "mcq", question: "Lalitpur is also known as…", choices: ["Kathmandu", "Patan", "Kirtipur", "Thimi"], answer: 1 },
  { id: "n73", category: "Cities", type: "mcq", question: "Which Valley city is famous for woodcarving and pottery?", choices: ["Kathmandu", "Bhaktapur", "Kirtipur", "Dhulikhel"], answer: 1 },
  { id: "n74", category: "Cities", type: "mcq", question: "Lukla is best known as…", choices: ["A border market", "The gateway town for Everest treks", "A lakeside resort", "An industrial city"], answer: 1 },
  { id: "n75", category: "Cities", type: "mcq", question: "Jomsom is the main town of…", choices: ["Mustang", "Manang", "Dolpa", "Humla"], answer: 0 },
  { id: "n76", category: "Cities", type: "mcq", question: "Namche Bazaar is a Sherpa market town on the way to…", choices: ["Everest Base Camp", "Annapurna Circuit", "Langtang", "Upper Mustang"], answer: 0 },
  { id: "n77", category: "Cities", type: "mcq", question: "Bandipur is best known as…", choices: ["A scenic hilltop Newar town", "A Terai market", "A border crossing", "A ski resort"], answer: 0 },
  { id: "n78", category: "Cities", type: "mcq", question: "Which city hosts the famous Janaki temple?", choices: ["Birgunj", "Janakpur", "Lahan", "Rajbiraj"], answer: 1 },
  { id: "n79", category: "Landmarks", type: "mcq", question: "Sagarmatha is the Nepali name for…", choices: ["Annapurna", "Mount Everest", "Machhapuchhre", "Dhaulagiri"], answer: 1 },
  { id: "n80", category: "Landmarks", type: "mcq", question: "Chitwan National Park is famous for…", choices: ["One-horned rhinos", "Polar bears", "Penguins", "Kangaroos"], answer: 0 },
  { id: "n81", category: "Landmarks", type: "mcq", question: "Boudhanath is…", choices: ["A large Buddhist stupa in Kathmandu", "A hydropower dam", "A ski resort", "A seaport"], answer: 0 },
  { id: "n82", category: "Landmarks", type: "mcq", question: "Pashupatinath is a sacred temple of…", choices: ["Vishnu", "Shiva", "Buddha", "Brahma"], answer: 1 },
  { id: "n83", category: "Landmarks", type: "tf", question: "Swayambhunath is nicknamed the Monkey Temple.", choices: ["True", "False"], answer: 0 },
  { id: "n84", category: "Landmarks", type: "mcq", question: "Hanuman Dhoka is the old royal palace in…", choices: ["Kathmandu", "Patan", "Bhaktapur", "Gorkha"], answer: 0 },
  { id: "n85", category: "Landmarks", type: "mcq", question: "How many storeys does Nyatapola temple in Bhaktapur have?", choices: ["Three", "Four", "Five", "Seven"], answer: 2 },
  { id: "n86", category: "Landmarks", type: "mcq", question: "Muktinath temple is in which district?", choices: ["Mustang", "Manang", "Dolpa", "Jumla"], answer: 0 },
  { id: "n87", category: "Landmarks", type: "mcq", question: "Manakamana temple is famously reached by…", choices: ["Cable car", "Railway", "Rope bridge", "Tunnel"], answer: 0 },
  { id: "n88", category: "Landmarks", type: "mcq", question: "Patale Chhango in Pokhara is better known as…", choices: ["Davis Falls", "Niagara Falls", "Victoria Falls", "Angel Falls"], answer: 0 },
  { id: "n89", category: "Landmarks", type: "mcq", question: "The World Peace Pagoda overlooks which city?", choices: ["Pokhara", "Kathmandu", "Lumbini", "Biratnagar"], answer: 0 },
  { id: "n90", category: "Landmarks", type: "mcq", question: "Sarangkot near Pokhara is famous for…", choices: ["Sunrise views of the Annapurnas", "White-water rafting", "Tea gardens", "Hot springs"], answer: 0 },
  { id: "n91", category: "Landmarks", type: "mcq", question: "Gupteshwor in Pokhara is a famous…", choices: ["Cave", "Lake", "Palace", "Fort"], answer: 0 },
  { id: "n92", category: "Landmarks", type: "mcq", question: "The Maya Devi Temple marks…", choices: ["The coronation site of kings", "The exact birth spot of the Buddha", "The tallest stupa", "The oldest palace"], answer: 1 },
  { id: "n93", category: "Landmarks", type: "tf", question: "An ancient Ashoka pillar stands at Lumbini.", choices: ["True", "False"], answer: 0 },
  { id: "n94", category: "Landmarks", type: "mcq", question: "Changu Narayan is regarded as one of the oldest temples in…", choices: ["The Kathmandu Valley", "Pokhara", "Lumbini", "Janakpur"], answer: 0 },
  { id: "n95", category: "Culture", type: "mcq", question: "Dashain is…", choices: ["Nepal's biggest Hindu festival", "A mountain", "A river", "A currency"], answer: 0 },
  { id: "n96", category: "Culture", type: "mcq", question: "Tihar is also known as the festival of…", choices: ["Kites", "Lights", "Boats", "Snow"], answer: 1 },
  { id: "n97", category: "Culture", type: "mcq", question: "Holi is the festival of…", choices: ["Colours", "Lights", "Kites", "Harvest"], answer: 0 },
  { id: "n98", category: "Culture", type: "mcq", question: "Teej is celebrated mainly by…", choices: ["Children", "Women", "Farmers", "Soldiers"], answer: 1 },
  { id: "n99", category: "Culture", type: "mcq", question: "Chhath festival is dedicated to…", choices: ["The moon", "The sun god", "The river goddess", "The harvest"], answer: 1 },
  { id: "n100", category: "Culture", type: "mcq", question: "Maghe Sankranti is observed in the month of…", choices: ["Magh", "Baisakh", "Kartik", "Shrawan"], answer: 0 },
  { id: "n101", category: "Culture", type: "mcq", question: "Buddha Jayanti celebrates…", choices: ["The harvest", "The birth of Lord Buddha", "The new year", "The full moon eclipse"], answer: 1 },
  { id: "n102", category: "Culture", type: "mcq", question: "What is momo?", choices: ["A drum", "A dumpling dish", "A hat", "A dance"], answer: 1 },
  { id: "n103", category: "Culture", type: "mcq", question: "Dal bhat consists mainly of…", choices: ["Noodles and soup", "Lentils and rice", "Bread and cheese", "Meat and potatoes"], answer: 1 },
  { id: "n104", category: "Culture", type: "mcq", question: "Sel roti is a…", choices: ["Ring-shaped rice bread", "Spicy curry", "Sweet milk cake", "Corn pancake"], answer: 0 },
  { id: "n105", category: "Culture", type: "mcq", question: "Tongba is a traditional warm drink of which community?", choices: ["Limbu", "Tharu", "Newar", "Sherpa"], answer: 0 },
  { id: "n106", category: "Culture", type: "mcq", question: "Daura suruwal is…", choices: ["A traditional men's attire", "A wedding dance", "A rice dish", "A musical instrument"], answer: 0 },
  { id: "n107", category: "Culture", type: "mcq", question: "Dhaka topi is a traditional…", choices: ["Cap", "Shawl", "Shoe", "Bag"], answer: 0 },
  { id: "n108", category: "Culture", type: "mcq", question: "The Kumari tradition is associated with…", choices: ["A living goddess", "A mountain festival", "A river ritual", "A harvest dance"], answer: 0 },
];
