// KamKhoj Play — typed game registry (metadata only; components lazy-load).

import type { GameMeta } from "./types";

export const GAMES: GameMeta[] = [
  {
    id: "reaction", title: "Reaction Lab", tagline: "How fast are your reflexes?",
    description: "Test raw reaction speed across classic, multi-round, sequence and precision modes.",
    category: ["reflex", "quick"], minutes: 2,
    instructions: ["Wait for the green signal, then tap as fast as you can.", "Tapping too early voids the trial.", "Play all modes to train different reflex skills."],
    controls: ["Mouse / touch: tap the pad", "Space: start trial"],
    supportsResume: false,
  },
  {
    id: "typing", title: "Typing Arena", tagline: "WPM, accuracy, consistency.",
    description: "High-quality typing tests with live character feedback and detailed results.",
    category: ["typing", "quick"], minutes: 3,
    instructions: ["Type the highlighted passage as fast and accurately as you can.", "Backspace fixes mistakes; paste is disabled.", "Pick a time or word-count mode."],
    controls: ["Keyboard: type", "Mobile: on-screen keyboard via the input"],
    supportsResume: false,
  },
  {
    id: "snake", title: "Snake", tagline: "The timeless arcade classic.",
    description: "Eat, grow, and survive as the speed climbs. Keyboard, swipe and pad controls.",
    category: ["classic", "quick"], minutes: 5,
    instructions: ["Eat food to grow and score.", "Avoid walls and your own tail.", "Speed increases as you eat."],
    controls: ["Arrows / WASD: steer", "Swipe: steer on touch", "Space: pause"],
    supportsResume: false,
  },
  {
    id: "merge", title: "Merge 2048", tagline: "Slide, merge, reach 2048.",
    description: "A smooth sliding number puzzle with undo, persistence and win detection.",
    category: ["puzzle", "classic"], minutes: 10,
    instructions: ["Slide tiles to merge matching numbers.", "Reach 2048 to win — or keep going.", "One undo per run; unfinished runs auto-save."],
    controls: ["Arrows / WASD: slide", "Swipe: slide on touch", "U: undo"],
    supportsResume: true,
  },
  {
    id: "memory", title: "Memory Match", tagline: "Flip, remember, pair up.",
    description: "Card matching across 4 difficulties and 5 themes, including a Nepal deck.",
    category: ["memory", "puzzle"], minutes: 5,
    instructions: ["Flip two cards per move and find every pair.", "Fewer moves and mistakes earn bigger scores.", "Combos reward consecutive matches."],
    controls: ["Mouse / touch: flip cards"],
    supportsResume: false,
  },
  {
    id: "sudoku", title: "Sudoku", tagline: "Pure logic, zero luck.",
    description: "Full Sudoku with notes mode, mistake limits, hints-free validation and resume.",
    category: ["puzzle", "classic"], minutes: 15,
    instructions: ["Fill every row, column and 3×3 box with 1–9.", "Use notes mode to pencil in candidates.", "Unfinished puzzles auto-save."],
    controls: ["1–9: enter number", "N: notes mode", "Backspace: erase"],
    supportsResume: true,
  },
  {
    id: "math", title: "Math Rush", tagline: "60 seconds of arithmetic.",
    description: "Timed arithmetic across operations with 60s, survival and zen modes.",
    category: ["puzzle", "quick"], minutes: 2,
    instructions: ["Answer as many as you can before time runs out.", "Survival ends on a wrong answer (with lives).", "Zen mode has no timer — just flow."],
    controls: ["Keyboard: type answer + Enter", "Touch: on-screen keypad"],
    supportsResume: false,
  },
  {
    id: "scramble", title: "Word Scramble", tagline: "Unjumble the letters.",
    description: "A large built-in word bank across 7 categories with hints and streaks.",
    category: ["knowledge", "quick"], minutes: 3,
    instructions: ["Unscramble each word before the timer ends.", "Hints cost streak progress; skips reset the streak.", "Longer words score more."],
    controls: ["Keyboard: type + Enter", "Touch: buttons"],
    supportsResume: false,
  },
  {
    id: "hangman", title: "Hangman", tagline: "Guess the word, beat the gallows.",
    description: "Polished word guessing with 6 categories, hints and difficulty levels.",
    category: ["knowledge", "classic"], minutes: 4,
    instructions: ["Guess letters to reveal the hidden word.", "Too many wrong guesses ends the round.", "Hints reveal a letter but lower your score."],
    controls: ["Keyboard: type letters", "Touch: letter grid"],
    supportsResume: false,
  },
  {
    id: "color", title: "Color Clash", tagline: "Don't trust the word.",
    description: "A Stroop-effect game: match the meaning or the ink, as the rule flips.",
    category: ["reflex", "quick"], minutes: 2,
    instructions: ["Follow the current rule: pick the WORD or the INK color.", "The rule can flip mid-run at higher levels.", "Combos multiply your score."],
    controls: ["Mouse / touch: tap a color"],
    supportsResume: false,
  },
  {
    id: "aim", title: "Aim Trainer", tagline: "Click fast. Miss little.",
    description: "Reflex aim training with time and target-count modes plus precision scoring.",
    category: ["reflex"], minutes: 2,
    instructions: ["Hit targets as they spawn inside the arena.", "Misses hurt accuracy; fast hits build score.", "Targets stay inside the visible arena."],
    controls: ["Mouse / touch: tap targets"],
    supportsResume: false,
  },
  {
    id: "sequence", title: "Sequence Memory", tagline: "Watch, remember, repeat.",
    description: "Simon-style sequence memory with light + tone cues (visual-first).",
    category: ["memory"], minutes: 4,
    instructions: ["Watch the sequence, then repeat it exactly.", "Each round adds one step.", "Keyboard 1–4 also works."],
    controls: ["Mouse / touch: tap pads", "1–4: pads"],
    supportsResume: false,
  },
  {
    id: "number-memory", title: "Number Memory", tagline: "How many digits fit?",
    description: "A number flashes briefly — type it back. Length grows with success.",
    category: ["memory", "quick"], minutes: 3,
    instructions: ["Memorize the number before it hides.", "Type it exactly to level up.", "Display time scales with digit count."],
    controls: ["Keyboard: type digits + Enter"],
    supportsResume: false,
  },
  {
    id: "visual-memory", title: "Visual Memory", tagline: "Hold the pattern.",
    description: "Highlighted cells flash, then hide. Recall them all as grids grow.",
    category: ["memory", "puzzle"], minutes: 4,
    instructions: ["Memorize the highlighted cells.", "Tap exactly those cells after they hide.", "Grid and count grow each level."],
    controls: ["Mouse / touch: tap cells"],
    supportsResume: false,
  },
  {
    id: "nepal", title: "Nepal Challenge", tagline: "How well do you know Nepal?",
    description: "The standout quiz: provinces, districts, cities, landmarks and culture.",
    category: ["knowledge", "nepal"], minutes: 5,
    instructions: ["Answer 10 questions per run.", "Categories rotate; explanations included.", "True/false and multiple choice."],
    controls: ["Mouse / touch: pick answers", "1–4: answer"],
    supportsResume: false,
  },
  {
    id: "quiz", title: "Quiz Arena", tagline: "8 packs, 4 modes.",
    description: "A reusable quiz engine: science, tech, world, history, sports and more.",
    category: ["knowledge"], minutes: 5,
    instructions: ["Pick a category pack and mode.", "Survival ends on the first wrong answer.", "Timed mode races a 90-second clock."],
    controls: ["Mouse / touch: pick answers", "1–4: answer"],
    supportsResume: false,
  },
  {
    id: "tictactoe", title: "Tic-Tac-Toe", tagline: "Beat the unbeatable.",
    description: "Vs computer (easy/medium/impossible minimax) or local 2-player.",
    category: ["classic", "puzzle"], minutes: 3,
    instructions: ["Get three in a row to win.", "Impossible mode plays perfectly.", "Track match stats across sessions."],
    controls: ["Mouse / touch: tap a square"],
    supportsResume: false,
  },
  {
    id: "connect4", title: "Connect Four", tagline: "Four in a row wins.",
    description: "Drop discs with real win detection and three AI difficulties.",
    category: ["classic", "puzzle"], minutes: 5,
    instructions: ["Connect four discs horizontally, vertically or diagonally.", "AI thinks asynchronously — UI never freezes.", "Local 2-player supported."],
    controls: ["Mouse / touch: tap a column"],
    supportsResume: false,
  },
  {
    id: "minesweeper", title: "Minesweeper", tagline: "Clear the field.",
    description: "Full Minesweeper: safe first click, flood reveal, flags, custom boards.",
    category: ["classic", "puzzle"], minutes: 8,
    instructions: ["Reveal every safe cell without hitting a mine.", "First click is always safe.", "Long-press (or flag mode) toggles flags on touch."],
    controls: ["Left click: reveal", "Right click: flag", "Touch: flag-mode toggle"],
    supportsResume: false,
  },
  {
    id: "sliding", title: "Sliding Puzzle", tagline: "Slide into place.",
    description: "3×3, 4×4 and 5×5 sliding puzzles — always solvable, auto-saved.",
    category: ["puzzle", "classic"], minutes: 8,
    instructions: ["Slide tiles into numbered order with the blank at the end.", "Only solvable shuffles are generated.", "Runs auto-save so you can continue later."],
    controls: ["Mouse / touch: tap a tile next to the blank", "Arrows: move tiles"],
    supportsResume: true,
  },
];

export const GAME_MAP: Record<string, GameMeta> = Object.fromEntries(GAMES.map((g) => [g.id, g]));

export const PLAY_CATEGORIES = [
  { id: "all", label: "All games" },
  { id: "quick", label: "Quick" },
  { id: "puzzle", label: "Puzzle" },
  { id: "memory", label: "Memory" },
  { id: "reflex", label: "Reflex" },
  { id: "typing", label: "Typing" },
  { id: "knowledge", label: "Knowledge" },
  { id: "classic", label: "Classic" },
  { id: "nepal", label: "Nepal" },
] as const;
